os: linux
dist: focal

stages:
  - build-web
  - build-app
  - release

jobs:
  include:
    - stage: build-web
      workspaces:
        create:
          name: web-build
          paths:
            - $TRAVIS_BUILD_DIR/web/dist/web-app-gz
      language: node_js
      node_js: 14
      script:
      - cd web
      - npm install
      - npm run build   
    - stage: build-app      
      workspaces:
        create:
          name: app-build
          paths:
            - $TRAVIS_BUILD_DIR/build
        use:
          - web-build
      language: shell
      addons:
        apt:
          packages:
          - git
          - wget
          - flex
          - bison
          - gperf
          - python3
          - python3-pip
          - python3-setuptools
          - cmake
          - ninja-build
          - ccache
          - libffi-dev
          - libssl-dev
      install:
      - mkdir ~/esp
      - cd ~/esp
      - git clone -b release/v4.1 --recursive https://github.com/espressif/esp-idf.git
      - cd ~/esp/esp-idf
      - "./install.sh"
      - ". ~/esp/esp-idf/export.sh"
      script:
      - cd $TRAVIS_BUILD_DIR
      - idf.py reconfigure
      - idf.py build
      - idf.py size
    - stage: release
      workspaces:
        use:
          - app-build
      script:
      - echo "Deploy"    
      before_deploy:
      - git config --local user.name "travis"
      - git config --local user.email "travis"
      - export TRAVIS_TAG="master-$TRAVIS_BUILD_NUMBER"
      - git tag $TRAVIS_TAG
      - echo "TRAVIS_TAG=${TRAVIS_TAG}"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file:
        - build/esp32-evse.bin
        - build/www.bin
        on:
          repo: dzurikmiroslav/esp32-evse
    
branches:
  only:
  - master
