os: linux
dist: focal

stages:
  - build-web
  - build-app
  - deploy

jobs:
  include:
    - stage: build-web
      language: node_js
      node_js: 14
      script:
      - cd $TRAVIS_BUILD_DIR/web
      - npm install
      - npm run build
    - stage: build-app
      language: shell
      addons:
        apt:
          packages:
          - git
          - wget
          - flex
          - bison
          - gperf
          - python3
          - python3-pip
          - python3-setuptools
          - cmake
          - ninja-build
          - ccache
          - libffi-dev
          - libssl-dev
      install:
      - mkdir ~/esp
      - cd ~/esp
      - git clone -b release/v4.1 --recursive https://github.com/espressif/esp-idf.git
      - cd ~/esp/esp-idf
      - "./install.sh"
      - ". ~/esp/esp-idf/export.sh"
      script:
      - cd $TRAVIS_BUILD_DIR
      - idf.py reconfigure
      - idf.py build
      - idf.py size

branches:
  only:
  - master
# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: build/esp32-evse.bin
#   on:
#     repo: dzurikmiroslav/esp32-evse
