os: linux
dist: focal
language: shell
addons:
  apt:
    packages:
    - git
    - wget
    - flex
    - bison
    - gperf
    - python3
    - python3-pip
    - python3-setuptools
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev
install:
- mkdir ~/esp
- cd ~/esp
- git clone -b release/v4.1 --recursive https://github.com/espressif/esp-idf.git
- cd ~/esp/esp-idf
- "./install.sh"
- ". ~/esp/esp-idf/export.sh"
script:
- cd $TRAVIS_BUILD_DIR
- idf.py reconfigure
- idf.py build
- idf.py size
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: HxTZJSqjGzJxDftz8mlrQDLBNk4C9PVAzFjclGG82b4qkmgh3e3reqFlhpRMqQp/lVRJBvLwqkCqJeOPyW+wxo+SsbbWS3sPjmc6jQ2YFPnAAodAK6p1/sC4MDeJ6twH5M4tqWrqicRKnes6gtAwn9GxOfS3D/1yvL7RFZtinI/BfyeiGcN8rRPILWZ07Uxns+y5drqr8NfufJWrPbBhecjk/cGCwLUzQnoOYxLoOYHF8kBupNfSqDShs4lpkSm7UAdDMTVJE7EtUwbak2Nu+tPuN7qorwaYODDzqqX+TeF/paUU0cRsi7+iU7yRh1TZPU9FTGXJV/q/jaK9n8/hrTK/NVvpNLPzg0HI5dgvZImdoBdbo7knPsCZwB4y3MsPyr2sDvpucJW4xCErHjht39dxNzk/XHlfA3AbdfJ1B+CPLCG2UtRLTnO4qOlH5NLDlNV9kgxVysE3uvmymZ871+x6MLQiduu3gaTXqUogabBRDnKFgT16rcyhba+0tRroZZh8rq/y4ilsJqQ0jsYYTUH96MrD4mI/Q6B3t5HGQ4MNTw1+hcXu7RAbJ0vBofqxz/PG2F2SempHgYctaqFY7GswLayLm4sO4/WT312HMKR30QYNQZfnAjc2CbkLHZkhKOZcYHP122StHbhUkmQ34YQec1To6Hqj4BS9ovLhmDE=
  file: build/esp32-evse.bin
  on:
    repo: dzurikmiroslav/esp32-evse
