os: linux
dist: focal
language: shell

addons:
  apt:
    packages:
    - git
    - wget
    - flex
    - bison
    - gperf
    - python3
    - python3-pip
    - python3-setuptools
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev
 
install:
- mkdir ~/esp
- cd ~/esp
- git clone -b release/v4.1 --recursive https://github.com/espressif/esp-idf.git
- cd ~/esp/esp-idf
- "./install.sh"
- ". ~/esp/esp-idf/export.sh"

script:
- cd $TRAVIS_BUILD_DIR
- idf.py reconfigure
- idf.py build
- idf.py size

# branches:
#   only:
#   - master
 
deploy:
  if: tag IS present
  provider: releases
  api_key: $GITHUB_TOKEN
  #skip_cleanup: true
  file:
  - build/esp32-evse.bin
  # name: Development
  prerelease: true
  # release_notes: Development
  #         tag_name: master-$TRAVIS_BUILD_NUMBER
  # overwrite: true
  on:
    repo: dzurikmiroslav/esp32-evse
