name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('payload is:');
            console.log(context.payload);
      
      - name: Upload release asset
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const fs = require('fs');

            const release = await github.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v1
            });
            
            console.log('release', { release });

  
#       - name: Checkout code
#         uses: actions/checkout@v2
#    
#       - name: Install ESP-IDF
#         uses: CalinRadoni/esp-idf-v4-action@v2
#         with:
#           esp_idf_version: 'v4.1'
#
#       - name: Build
#         run: |
#           source ~/esp/esp-idf/export.sh
#           idf.py reconfigure
#           idf.py app
#           idf.py size           
#      
#       - name: Upload release assets
#         if: startsWith(github.ref, 'refs/tags/')
#         uses: actions/github-script@v2
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const fs = require('fs');
#             github.repos.uploadReleaseAsset({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               release_id: context.payload.ref.replace(/\/refs\/tags\//, ''),
#               name: 'esp32-evse'
#               data: fs.readFileSync(`./build/esp32-evse.bin')
#             });
